### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by ExXxtr3me** [tiagorvmartins/portanexus#11]
Would it be possible to sort the containers alphabetically? Right now they seem pretty random.

**Comment by tiagorvmartins** [comment]
Yes can be done, will introduce it on next version, thank you for your feedback and interest!

**Comment by ExXxtr3me** [comment]
> Yes can be done, will introduce it on next version, thank you for your feedback and interest!

Awesome, thank you very much. 👍

**Comment by tiagorvmartins** [comment]
Hey @ExXxtr3me you request has been addressed on [v0.2.0](https://github.com/tiagorvmartins/portanexus/releases/tag/v0.2.0)
Let me know if it helps / you find any issues.
Thank you!

**Comment by ExXxtr3me** [comment]
Thank you, that's perfect. 👍
Just one thing, the version number in the app is still showing as 0.1.4.

**Comment by tiagorvmartins** [comment]
Thank you for raising it, totally forgot about it, it's updated now!

**Comment by tiagorvmartins** [comment]
Closing this one as completed.
